/**
 * Placeholder template — generated automatically by `npm run env:init`.
 * Do NOT edit this file or environment.prod.ts directly.
 *
 * To set real credentials:
 *   1. cp .env.local.example .env.local
 *   2. Fill in your values in .env.local
 *   3. npm run env:init   ← writes environment.prod.ts from .env.local
 *
 * With placeholder values the app runs in offline/demo mode.
 */

export const environment = {
  production: true,
  googleCalendar: {
    clientId: 'YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com'
  },
  // Firebase Console → Authentication → Sign-in method → Google → Web client ID
  googleAuthClientId: '',
  firebase: {
    apiKey: 'YOUR_FIREBASE_API_KEY',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    appId: 'YOUR_APP_ID'
  }
};
